input_noise_train: 0.03  # Add 0-mean white noise with std being a fraction of the mean input of train, to train inputs
input_noise_val: 0.00  # Add 0-mean white noise with std being a fraction of the mean input of train, to val inputs
skip_band10: False  # True --> Skip band 10 as input (may be needed for Skogsstyrelsen data)
skip_band1:  True  # True --> Skip band 1 (SKIP_BAND_1 should always be True, as the band currently does not make sense in the data; further work needed in that direction in future work)
inputs: ['spec_bands']  # Add keys from PROPERTY_COLUMN_MAPPING to use those as inputs
regressor: 'thick'  # Can be set to any other key in PROPERTY_COLUMN_MAPPING to regress that instead
uniform_dist_no_cloud_thin_cloud_reg_cloud: True  # Ensures that we train evenly in the 'clear', 'thin-cloud' and 'opaque-cloud' regimes
threshold_thickness_is_cloud: 0.025  # Cloud optical tickness (COT) above this --> seen as an 'opaque cloud' pixel
threshold_thickness_is_thin_cloud: 0.015  # Cloud optical tickness (COT) above this --> seen as a 'thin cloud' pixel
normalize_cot: False
cot_max: 50  # Used for normalization
num_workers: 0
shuffle: True
property_column_mapping:
  spec_bands: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
  angles: [14, 15, 16]
  thick: [17]
  type: [18]
  prof_id: [19]
  gas_vapour: [20, 21]
  surf_prof: [22]
spec_bands_stats:
  means: [0.64983555, 0.49675034, 0.47293043, 0.564903, 0.52927473, 0.65845986, 0.93623101, 0.90515048, 0.99451205,
          0.45604575, 0.07375108, 0.53309616, 0.43224668]
  stds: [0.35911874, 0.28274442, 0.27778134, 0.28483809, 0.31573642, 0.28173209, 0.31942519, 0.32981911, 0.36159493,
         0.29364748, 0.1140917, 0.41934613, 0.3335538]
